name: Daily Resume Update

on:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST
    - cron: '30 9 * * *'   # 3:00 PM IST
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          NAUKRI_EMAIL: ${{ secrets.NAUKRI_EMAIL }}
          NAUKRI_PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}
          FILE_ID: ${{ secrets.FILE_ID }}
          FORM_KEY: ${{ secrets.FORM_KEY }}
        run: python updateDaily.py
